language: node_js
node_js:
  - "6"
  - "8"
  - "10"
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
addons:
  chrome: stable
script: "./node_modules/karma/bin/karma start test/karma.conf.js --browsers Chrome_travis_ci --single-run --no-auto-watch --capture-timeout 300000"
cache: yarn